version: "3.5"

services:
  nginx:
    image: nginx:latest
    command: nginx-debug -g 'daemon off;'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT-8000}:80"
    depends_on:
      - api
      - frontend

  api:
    image: php:fpm-alpine3.13
    working_dir: /app
    volumes:
      - ../my-app:/app
    env_file:
      - ../my-app/.env
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
      DB_DATABASE: my_app
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    image: node:15.4-alpine3.12
    command: yarn dev
    working_dir: /app
    tty: true
    volumes:
      - ../frontend:/app
      - /app/node_modules

  postgres:
    image: postgres
    ports:
      - "${POSTGRES_PORT-5434}:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: my_app

  redis:
    image: redis:6-alpine
